export const TYPES_PASTEL: Record<string, string> = {
  normal: "bg-normal_pastel",
  fire: "bg-fire_pastel",
  water: "bg-water_pastel",
  grass: "bg-grass_pastel",
  electric: "bg-electric_pastel",
  ice: "bg-ice_pastel",
  fighting: "bg-fighting_pastel",
  poison: "bg-poison_pastel",
  ground: "bg-ground_pastel",
  flying: "bg-flying_pastel",
  psychic: "bg-psychic_pastel",
  bug: "bg-bug_pastel",
  rock: "bg-rock_pastel",
  ghost: "bg-ghost_pastel",
  dark: "bg-dark_pastel",
  dragon: "bg-dragon_pastel",
  steel: "bg-steel_pastel",
  fairy: "bg-fairy_pastel",
  default: "bg-default",
}
