name: Render.com deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy client to production
        env:
          deploy_url_front: ${{ secrets.RENDER_DEPLOY_HOOK_URL_FRONT }}
        run: |
          curl "$deploy_url_front"

      - name: Deploy server to production
        env:
          deploy_url_back: ${{ secrets.RENDER_DEPLOY_HOOK_URL_BACK }}
        run: |
          curl "$deploy_url_back"
