name: Render.com deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub Token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
