name: Bump minor version

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git identity
        run: |
          git config --global user.email "astrodaniel1234@gmail.com"
          git config --global user.name "dpMelian"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run release script
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
